"""added blog series to article

Revision ID: 054287c6cfc5
Revises: d5ff99e95f8a
Create Date: 2023-07-31 15:40:40.335503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054287c6cfc5'
down_revision = 'd5ff99e95f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('series')

    # ### end Alembic commands ###
