"""added blog series order to article

Revision ID: 24f73a201b45
Revises: 054287c6cfc5
Create Date: 2023-07-31 16:04:52.419811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f73a201b45'
down_revision = '054287c6cfc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seriesOrder', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('seriesOrder')

    # ### end Alembic commands ###
