"""increased techType charcount to 50

Revision ID: 33202e0a461a
Revises: 668ff392c2d9
Create Date: 2023-06-14 16:12:25.144305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33202e0a461a'
down_revision = '668ff392c2d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_stack', schema=None) as batch_op:
        batch_op.alter_column('techType',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_stack', schema=None) as batch_op:
        batch_op.alter_column('techType',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
