"""added TechStack table

Revision ID: 668ff392c2d9
Revises: 5cefc9b8d3d1
Create Date: 2023-06-14 13:46:07.053600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668ff392c2d9'
down_revision = '5cefc9b8d3d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tech_stack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('techType', sa.String(length=20), nullable=False),
    sa.Column('techName', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tech_stack')
    # ### end Alembic commands ###
