"""article body inc to 40k

Revision ID: d5ff99e95f8a
Revises: 14d537eeeb1c
Create Date: 2023-07-28 16:39:30.956153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ff99e95f8a'
down_revision = '14d537eeeb1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.TEXT(length=30000),
               type_=sa.Text(length=40000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.Text(length=40000),
               type_=sa.TEXT(length=30000),
               existing_nullable=False)

    # ### end Alembic commands ###
