"""changed article body to support mysql maxlen

Revision ID: d6fe2658e4ff
Revises: 2375e6b1a3f5
Create Date: 2023-07-21 09:12:51.770232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6fe2658e4ff'
down_revision = '2375e6b1a3f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.String(length=16383),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.String(length=16383),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=False)

    # ### end Alembic commands ###
